# https://docs.docker.com/compose/compose-file/
version: '3.8' 

services: 
    first_volume_exercise:  
      image: devopsdockeruh/first_volume_exercise
      build: . 
      volumes: 
          -./logs.txt:/usr/app/logs.txt
      container_name: volume_exercise 
