# let us try long syntax
version: "3.3"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - 5000:5000
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - 8000:8000
    volumes:
        - type: bind
          source: ./logs.txt
          target: /app_server/logs.txt
