FROM alpine

WORKDIR /app

RUN apk add --no-cache git nodejs nodejs-npm \
    && git clone https://github.com/docker-hy/frontend-example-docker.git . \
    && npm install

EXPOSE 5000
ENV API_URL=http://127.0.0.1:8000

CMD npm start
