# let us try from linux alpine
FROM alpine

WORKDIR /app_server
RUN apk add --no-cache git nodejs nodejs-npm \
    && git clone https://github.com/docker-hy/backend-example-docker.git . \
    && npm install
EXPOSE 8000
ENV FRONT_URL=http://127.0.0.1:5000
CMD npm start 
