version: '3.5' 

services: 
    backend:  
      build:
        context: .
        dockerfile: Dockerfile_b_end
      container_name: backend
      environment:
        - FRONT_URL=http://localhost     
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_NAME=my_postgres
        - DB_HOST=postgres        
    frontend:
      build:
        context: .
        dockerfile: Dockerfile_f_end
      ports:
         - 5000:5000
      environment:
         - API_URL=http://localhost/api
      container_name: frontend
    redis:
      image: redis
      container_name: redis
    postgres:
      image: postgres
      container_name: postgres
      environment:
        - POSRGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=my_postgres
    nginx:
      image: nginx
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
