version: '3.5' 

services: 
    backend:  
      build:
        context: .
        dockerfile: Dockerfile_b_end
      ports: 
        - 8000:8000
      container_name: backend
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_NAME=my_postgres
        - DB_HOST=postgres
      depends_on:
        - redis
        - postgres
        
    frontend:
      build:
        context: .
        dockerfile: Dockerfile_f_end
      ports: 
        - 5000:5000
      container_name: frontend
      depends_on: 
        - backend  
    redis:
      image: redis
      restart: unless-stopped
      container_name: redis
      
    postgres:
      image: postgres
      restart: unless-stopped
      container_name: postgres_db
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=my_postgres
