version: '3.3' 

services: 
    backend:  
      build:
        context: .
        dockerfile: Dockerfile_b_end
      ports: 
        - 8000:8000
      container_name: backend
      environment:
        - REDIS=redis
    frontend:
      build:
        context: .      
        dockerfile: Dockerfile_f_end
      ports: 
        - 5000:5000
      container_name: frontend
    redis:
      image: redis
      container_name: redis
